In [1]:
import json
import numpy as np
import pandas as pd
from westpy.qdet import QDETResult

effective_hamiltonian = QDETResult(filename='../pdep_4992.wfreq.save/wfreq.json')
#let M=0
occ=effective_hamiltonian.__dict__['occupation']
print("occ: ", occ)
nelec = (int(occ.sum()/2),int(occ.sum()/2))
# diagonalize Hamiltonian
solution = effective_hamiltonian.solve(nroots = 50, nelec=nelec)

 
 _    _ _____ _____ _____            
| |  | |  ___/  ___|_   _|           
| |  | | |__ \ `--.  | |_ __  _   _  
| |/\| |  __| `--. \ | | '_ \| | | | 
\  /\  / |___/\__/ / | | |_) | |_| | 
 \/  \/\____/\____/  \_/ .__/ \__, | 
                       | |     __/ | 
                       |_|    |___/  
 
WEST version     :  6.0.0
Today            :  2024-12-28 19:10:56.147298
occ:  [[1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
-----------------------------------------------------
Building effective Hamiltonian...
nspin: 2
occupations: [[1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


diag[1RDM - 1RDM(GS)]                                           \
   E [eV] char                  1240   1241   1242   1243   1244  1246   1247   
0   0.000   3-                 0.000  0.000  0.000  0.000  0.000 0.000  0.000   
1   0.113   2-                 0.008 -0.020 -0.010 -0.024 -0.001 0.000  0.015   
2   0.114   2-                 0.008 -0.016 -0.003 -0.035 -0.001 0.000  0.019   
3   0.187   2-                 0.012 -0.003 -0.031 -0.054 -0.001 0.001  0.033   
4   0.329   2-                 0.043 -0.209  0.089 -0.186  0.265 0.163 -0.052   
5   0.329   2-                 0.043  0.273 -0.393 -0.185  0.265 0.163 -0.052   
6   0.883   2-                 0.063 -0.279 -0.391  0.507  0.200 0.002 -0.049   
7   0.885   2-                 0.063 -0.270  0.044  0.063  0.200 0.002 -0.023   
8   0.930   2-                 0.066  0.119  0.067 -0.168  0.005 0.082 -0.051   
9   0.930   2-                 0.066  0.558 -0.367 -0.174  0.005 0.083 -0.051   
10  1.380   3-                -0.441  0.111  0.157  0.026  0.001 0.002 -0.009   
11  1.383   3-                -0.441  0.197  0.209 -0.113  0.001 0.002  0.097   
12  1.475   4-                -0.368  0.051  0.046  0.029  0.202 0.102 -0.025   
13  1.497   3-                -0.402  0.025  0.056  0.091  0.206 0.105 -0.028   
14  1.619   3-                -0.117  0.065 -0.033 -0.063  0.046 0.002  0.001   
15  1.635   3-                -0.429 -0.137  0.274  0.067 -0.003 0.001  0.052   
16  1.636   3-                -0.429  0.154  0.012  0.040 -0.003 0.002  0.096   
17  1.709   3-                -0.369 -0.039  0.017  0.222  0.158 0.001 -0.003   
18  1.709   3-                -0.369 -0.039  0.018  0.221  0.158 0.001 -0.003   
19  1.828   3-                -0.380 -0.040 -0.004  0.217  0.172 0.002  0.010   
20  1.840   3-                -0.423  0.076  0.043 -0.065  0.254 0.197 -0.025   
21  1.881   3-                -0.390 -0.041  0.011 -0.018  0.255 0.182  0.004   
22  1.881   3-                -0.390 -0.043  0.020 -0.025  0.255 0.180  0.007   
23  1.901   2-                -0.094  0.049 -0.046 -0.073  0.046 0.004 -0.016   
24  1.901   2-                -0.093  0.039 -0.048 -0.061  0.045 0.004 -0.018   
25  1.987   3-                -0.404 -0.021 -0.011 -0.039  0.264 0.182  0.022   
26  1.995   3-                -0.385  0.547  0.080 -0.164  0.020 0.043 -0.046   
27  2.065   2-                -0.047 -0.010 -0.068 -0.069  0.034 0.016 -0.023   
28  2.097   3-                -0.099 -0.249 -0.172  0.111  0.046 0.187  0.181   
29  2.121   2-                 0.075 -0.269 -0.388  0.003  0.545 0.180 -0.051   
30  2.200   2-                 0.011 -0.256 -0.246 -0.004 -0.004 0.240  0.246   
31  2.200   2-                 0.011 -0.256 -0.239 -0.010 -0.004 0.240  0.246   
32  2.227   3-                -0.307 -0.279 -0.031  0.355  0.151 0.056  0.064   
33  2.274   2-                 0.005 -0.238 -0.225 -0.023 -0.003 0.241  0.224   
34  2.452   2-                 0.044 -0.210 -0.393 -0.183  0.261 0.179  0.410   
35  2.452   2-                 0.044 -0.207 -0.396 -0.183  0.261 0.618 -0.029   
36  2.491   3-                -0.360  0.308  0.019 -0.017  0.007 0.067 -0.006   
37  2.531   2-                 0.044 -0.279 -0.380  0.199  0.228 0.007 -0.040   
38  2.533   2-                 0.043 -0.264 -0.220  0.022  0.229 0.010  0.174   
39  2.539   2-                 0.082  0.146 -0.388  0.020  0.233 0.043 -0.047   
40  2.590   3-                -0.196 -0.245 -0.166  0.216  0.304 0.122 -0.046   
41  2.592   3-                -0.205 -0.025 -0.212  0.049  0.309 0.127 -0.003   
42  2.597   3-                -0.338  0.257 -0.002 -0.030  0.013 0.069  0.014   
43  2.597   3-                -0.338  0.257  0.001 -0.032  0.012 0.068  0.015   
44  2.629   3-                -0.152 -0.268 -0.187  0.184  0.278 0.105 -0.047   
45  2.630   3-                -0.141 -0.078 -0.267  0.070  0.271 0.101  0.077   
46  2.696   3-                -0.329  0.262 -0.026 -0.051  0.017 0.066  0.024   
47  2.895   3-                -0.432 -0.085  0

-----------------------------------------------------


In [15]:
solution.keys()
solution['nelec']

(2, 2)

In [21]:
#np.shape(solution['evcs'][0])
from westpy.qdet import visualize_correlated_state
for i, state in enumerate(solution['evcs']):
    en = solution['evs'][i]
    print(f'i= {i}, en [eV]={en} Deter')
    multiwfc=visualize_correlated_state(state, solution['norb'], solution['nelec'], cutoff=10 **(-1))
    print(multiwfc)

i= 0, en [eV]=0.0 Deter
+0.173|0000000000011>|0000000000101>+0.469|0000000000011>|0000000001001>+0.188|0000000000011>|0000000001010>-0.305|0000000000011>|0000010000001>-0.154|0000000000011>|0000100000001>-0.186|0000000000011>|0001000000001>-0.456|0000000000101>|0000000000101>-0.183|0000000000101>|0000000000110>+0.178|0000000000101>|0000000001001>-0.298|0000000000101>|0000001000001>-0.184|0000000000101>|0000100000001>+0.146|0000000000101>|0001000000001>-0.146|0000000001010>|0000000001001>+0.142|0000000001100>|0000000000101>
i= 1, en [eV]=0.11345677261327157 Deter
-0.433|0000000000011>|0000000000101>-0.168|0000000000011>|0000000000110>-0.137|0000000000011>|0000000001001>-0.262|0000000000011>|0000001000001>+0.209|0000000000011>|0000010000001>+0.249|0000000000011>|0001000000001>-0.128|0000000000101>|0000000000101>+0.453|0000000000101>|0000000001001>+0.176|0000000000101>|0000000001010>-0.208|0000000000101>|0000001000001>-0.281|0000000000101>|0000010000001>-0.258|0000000000101>|0000100000001

In [2]:
solution2 = effective_hamiltonian.solve(nroots = 50, nelec=(3,1))

-----------------------------------------------------
Building effective Hamiltonian...
nspin: 2
occupations: [[1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


diag[1RDM - 1RDM(GS)]                                     \
   E [eV] char                  1240   1241   1242   1243   1244   1246   
0   0.000   3-                 0.000  0.000  0.000  0.000  0.000  0.000   
1   0.208   3-                 0.099 -0.536 -0.009  0.243  0.184 -0.001   
2   0.208   3-                 0.099 -0.063 -0.483  0.243  0.184 -0.001   
3   1.352   4-                -0.370 -0.161 -0.021  0.323  0.167  0.006   
4   1.484   4-                -0.382 -0.082 -0.002  0.167 -0.017  0.001   
5   1.489   4-                -0.382 -0.081  0.182 -0.017 -0.017  0.001   
6   1.504   4-                -0.376 -0.047 -0.002 -0.024  0.239  0.197   
7   1.688   3-                -0.373 -0.182 -0.061  0.360  0.166  0.002   
8   1.704   4-                -0.353 -0.329 -0.081  0.411  0.174  0.005   
9   1.704   4-                -0.353 -0.341 -0.056  0.397  0.174  0.004   
10  1.805   4-                -0.326 -0.318 -0.111  0.358  0.161  0.022   
11  1.920   3-                 0.056 -0.328 -0.189  0.095  0.057  0.102   
12  1.920   3-                 0.055 -0.223 -0.294  0.095  0.057  0.096   
13  1.924   3-                -0.010 -0.252 -0.242  0.027  0.006  0.217   
14  1.999   3-                 0.004 -0.235 -0.235 -0.002 -0.007  0.226   
15  2.068   3-                 0.058 -0.294 -0.222  0.062  0.028  0.121   
16  2.068   3-                 0.058 -0.246 -0.270  0.061  0.028  0.121   
17  2.222   3-                -0.293  0.229 -0.012 -0.018  0.002  0.064   
18  2.325   3-                 0.104 -0.548 -0.490  0.235  0.183  0.031   
19  2.325   3-                 0.104 -0.546 -0.492  0.235  0.183  0.458   
20  2.439   4-                -0.344 -0.567 -0.005  0.212  0.464  0.226   
21  2.439   4-                -0.344 -0.084 -0.489  0.212  0.464  0.226   
22  2.800   3-                 0.091 -0.259 -0.286 -0.022 -0.016  0.011   
23  2.802   3-                 0.081 -0.372 -0.161 -0.021 -0.015  0.017   
24  2.805   3-                 0.076 -0.319 -0.210 -0.016 -0.009  0.012   
25  2.805   3-                 0.076 -0.210 -0.320 -0.015 -0.009  0.010   
26  2.859   3-                -0.308 -0.133 -0.024  0.197  0.212  0.015   
27  2.859   3-                -0.308  0.310 -0.469  0.198  0.212  0.017   
28  3.092   3-                 0.125 -0.554 -0.489  0.452  0.387  0.000   
29  3.218   4-                -0.340 -0.259 -0.074  0.237  0.095  0.014   
30  3.280   4-                -0.381 -0.218 -0.234  0.160 -0.012  0.258   
31  3.284   4-                -0.379 -0.379  0.019  0.062 -0.012  0.135   
32  3.328   4-                -0.368 -0.319 -0.188  0.297  0.162  0.022   
33  3.375   3-                -0.688 -0.104  0.192  0.212  0.083  0.023   
34  3.382   3-                -0.717 -0.102 -0.013  0.439  0.096  0.020   
35  3.423   4-                -0.367 -0.338 -0.194  0.069  0.163  0.311   
36  3.430   4-                -0.352 -0.369 -0.111  0.235  0.074  0.068   
37  3.431   4-                -0.352 -0.290 -0.141  0.184  0.077  0.120   
38  3.439   4-                -0.366 -0.277 -0.200  0.071  0.126  0.269   
39  3.463   4-                -0.328 -0.233 -0.258  0.133  0.003  0.159   
40  3.464   4-                -0.321 -0.365 -0.023  0.038  0.008  0.195   
41  3.470   3-                -0.370 -0.286 -0.129  0.097  0.027  0.203   
42  3.470   4-                -0.369 -0.314 -0.228  0.228  0.129  0.227   
43  3.489   4-                -0.268 -0.302 -0.185  0.049  0.163  0.218   
44  3.489   4-                -0.240 -0.245 -0.269  0.067  0.162  0.207   
45  3.509   3-                -0.307 -0.278 -0.267  0.069  0.160  0.306   
46  3.510   3-                -0.317 -0.330 -0.185  0.046  0.156  0.283   
47  3.517   4-                -0.369 -0.356 -0.245  0.178  0.191  0.309   
48  3.529   4-                -0.369 -0.284 -0.224  0.102  0.174  0.296   
49  3.533   4-                -0.200 -0.338 -0.137  0.131  0.093  0.111   

                                                   
     1247   1248   1249   1250   1255  1256  1257  
0   0.000 

-----------------------------------------------------


In [22]:
from westpy.qdet import visualize_correlated_state
for i, state in enumerate(solution2['evcs']):
    en = solution2['evs'][i]
    print(f'i= {i}, en [eV]={en} Deter')
    multiwfc=visualize_correlated_state(state, solution2['norb'], solution2['nelec'], cutoff=10 **(-1))
    print(multiwfc)

i= 0, en [eV]=0.0 Deter
+0.824|0000000000111>|0000000000001>+0.381|0000000000111>|0000000000010>-0.225|0000000000111>|0000000010000>+0.266|0000000001110>|0000000000001>-0.140|0000000010110>|0000000000001>
i= 1, en [eV]=0.20814760326486909 Deter
-0.109|0000000001011>|0000000000001>+0.686|0000000001101>|0000000000001>+0.158|0000000001101>|0000000000010>-0.118|0000000001101>|0000000010000>+0.580|0000000010101>|0000000000001>+0.156|0000000010101>|0000000000010>-0.111|0000000010101>|0000000010000>-0.185|0000000011100>|0000000000001>-0.211|0000010000101>|0000000000001>
i= 2, en [eV]=0.2082544090420467 Deter
+0.686|0000000001011>|0000000000001>+0.158|0000000001011>|0000000000010>-0.118|0000000001011>|0000000010000>+0.109|0000000001101>|0000000000001>+0.580|0000000010011>|0000000000001>+0.156|0000000010011>|0000000000010>-0.111|0000000010011>|0000000010000>-0.185|0000000011010>|0000000000001>-0.211|0000010000011>|0000000000001>
i= 3, en [eV]=1.3521658432433319 Deter
+0.133|0000000000111>|00000